{% set version = "1.1.1" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 34c7b4c5fc5b6ba65982dca55daceaa371a9003d8da7fe0f952e076e07e53910

build:
  number: 0
  skip: True  # [py<37]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Optional dependencies are numpy, python-lz4, psutil

test:
  requires:
    - pip
    - python
    - pytest
  commands:
    - pip check
    - pytest --pyargs joblib -k 'not test_memory_integration'
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend

about:
  home: https://joblib.readthedocs.io/en/latest/
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://joblib.readthedocs.io/en/latest/
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
