{% set version = "0.14.0" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 9e66f3e31669f772fcbad95043fd05e4530e78288d60363b785d4c288a5dc707

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - joblib

about:
  home: http://packages.python.org/joblib/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python function as pipeline jobs.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
