{% set name = "joblib" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8561a3269e6801106863fd0d6d84bb737be9e7631e33aaed3fb9ce5953688da3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
  run:
    - python

# Disabled unstable tests with timelimits:
{% set deselect_tests = " --deselect=test_memory.py" %}
{% set deselect_tests = deselect_tests + " --deselect=test_memory_async.py" %}

test:
  source_files:
    - conftest.py
    - pyproject.toml
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
    - python -c "import multiprocessing as mp; print('multiprocessing.cpu_count():', mp.cpu_count())"
    - python -c "import joblib; print('joblib.cpu_count():', joblib.cpu_count())"
    - pytest --pyargs joblib.test {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - threadpoolctl

about:
  home: https://joblib.readthedocs.io
  summary: Lightweight pipelining - using Python functions as pipeline jobs.
  description: |
    A set of tools to provide lightweight pipelining in Python. In particular:
    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),
    easy, simple parallel computing. Joblib is optimized to be fast and robust on
    large data in particular and has specific optimizations for numpy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://joblib.readthedocs.io
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
