{% set name = "joblib" %}
{% set version = "1.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3faa5c39054b2f03ca547da9b2f52fde67c06240c31853f306aea97f13647b55

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.2
  run:
    - python

# Disabled unstable tests with timelimits:
# E   AssertionError: assert 1754034008.6817126 == 1754034008.546659
{% set tests_to_skip = "test__get_items" %}
{% set tests_to_skip = tests_to_skip + " or test__get_items_to_delete" %}
{% set tests_to_skip = tests_to_skip + " or test_call_and_shelve_lazily_load_stored_result" %}
{% set tests_to_skip = tests_to_skip + " or test_memory_reduce_size_bytes_limit" %}
{% set tests_to_skip = tests_to_skip + " or test_memory_reduce_size_items_limit" %}
{% set tests_to_skip = tests_to_skip + " or test_memory_reduce_size_age_limit" %}
{% set tests_to_skip = tests_to_skip + " or test_parallel_with_unpicklable_functions_in_args" %} # [win]
# E   OSError: [Errno 63] File name too long
{% set tests_to_skip = tests_to_skip + " or test_memory_integration" %}
{% set tests_to_skip = tests_to_skip + " or test_memory_integration_async" %}

test:
  source_files:
    - conftest.py
    - pyproject.toml
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
    - python -c "import multiprocessing as mp; print('multiprocessing.cpu_count():', mp.cpu_count())"
    - python -c "import joblib; print('joblib.cpu_count():', joblib.cpu_count())"
    - pytest --pyargs joblib.test -k "not ({{ tests_to_skip }})"
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - threadpoolctl


about:
  home: https://joblib.readthedocs.io
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  description: |
    "A set of tools to provide lightweight pipelining in Python. In particular:
    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),
    easy, simple parallel computing. Joblib is optimized to be fast and robust on
    large data in particular and has specific optimizations for numpy arrays."
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://joblib.readthedocs.io
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
