{% set version = "1.4.2" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 1d95f5f3ab303be89aa4666956bf05a589f56e52c29b836267c8e3885223ff90

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
    - pytest  # pytest is needed for some imports
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend

about:
  home: https://joblib.readthedocs.io/
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  description: |
    "A set of tools to provide lightweight pipelining in Python. In particular:
    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),
    easy simple parallel computing. Joblib is optimized to be fast and robust on
    large data in particular and has specific optimizations for numpy arrays."
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/joblib/joblib/blob/{{ version }}/LICENSE.txt
  doc_url: https://joblib.readthedocs.io/
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
