{% set version = "1.1.1" %}

package:
  name: joblib
  version: {{ version }}

source:
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: 4cda464ca712a4814849c9477d7551b696ce215dc05d79fc516460814ef48f4f
  patches:
      - CVE-2022-21797.patch

build:
  number: 1
  skip: True  # [py<36]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Optional dependencies are numpy, python-lz4, psutil

test:
  requires:
    - pip
    - pytest  # pytest is needed for some imports
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend

about:
  home: https://joblib.readthedocs.io/en/latest/
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
  description: |
    "A set of tools to provide lightweight pipelining in Python. In particular:
    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),
    easy simple parallel computing. Joblib is optimized to be fast and robust on
    large data in particular and has specific optimizations for numpy arrays."
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  license_url: https://github.com/joblib/joblib/blob/{{ version }}/LICENSE.txt
  doc_url: https://joblib.readthedocs.io/en/latest/
  doc_source_url: https://github.com/joblib/joblib/tree/{{ version }}/doc
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
