{% set name = "joblib" %}
{% set version = "1.6.0" %}
{% set deselect_tests = " --deselect=test_memory.py" %}
{% set deselect_tests = deselect_tests + " --deselect=test_memory_async.py" %}

# Disabled unstable tests with timelimits:
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ccc96785b12046c08fd6d55839c12857831b54a3c1673ffadd2f04bfc4eda03

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=77.0.3
    - cython
  run:
    - python
    - cloudpickle >=3.0

test:
  source_files:
    - conftest.py
    - pyproject.toml
  imports:
    - joblib
    - joblib.externals
    - joblib.test
    - joblib.test.data
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
    - python -c "import multiprocessing as mp; print('multiprocessing.cpu_count():', mp.cpu_count())"
    - python -c "import joblib; print('joblib.cpu_count():', joblib.cpu_count())"
    - pytest --pyargs joblib.test {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - pytest-timeout
    - threadpoolctl

about:
  home: https://joblib.readthedocs.io
  summary: Lightweight pipelining - using Python functions as pipeline jobs.
  description: |
    A set of tools to provide lightweight pipelining in Python. In particular:
    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),
    easy, simple parallel computing. Joblib is optimized to be fast and robust on
    large data in particular and has specific optimizations for numpy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://joblib.readthedocs.io
  dev_url: https://github.com/joblib/joblib

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
    - ogrisel
    - lesteve
    - tomMoral
    - pierreglaser
