{% set version = "0.12" %}

package:
  name: joblib
  version: {{ version }}

source:
  fn: joblib-{{ version }}.tar.gz
  url: https://github.com/joblib/joblib/archive/{{ version }}.tar.gz
  sha256: c6a00819f1d872a48818c14dbaa495c5806eb7f48af37207398d3a36f12f42d0

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - joblib

about:
  home: http://packages.python.org/joblib/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Python function as pipeline jobs.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
