travis:
  secure:
    BINSTAR_TOKEN: g6izGJzPW75pQHtDy+dXn3swJWjE6vEpyPLKYV2wZKTeZiRuJbSEJ5KnfCfZKUtbSsAssbe2PnWrumNdKXjea9LCKrlTMJTokiu7LutlpWeTJJLAhs2IMFR01RhHJg79DFg0NlqUlL7UBakTaF9ci0Z3WegiiF+++VAoLsMwehcHHKSthJzWTmjiz4vA29YbWl4UoVm0yYAYy0MknlqUuOdi4nwzvtR4yBKuEngRAjjaPFw03W6WsMlYTzEx4vaC/cFytTAIpoUHxKlRFAcxf96UOD0mBXiyRIBYJDr7XxT0505C9iie2FZzrO4FxBmleDtDTuZnPFEnjjpEbzowUbPBgOjNVxVzMf51tFMR8V58aVoyAvCTSD1hS2Xjg3/u9uvrMCAK9zFGbNphG5qrR/gIf8mN1VXS5kZW04MlcGWSYOUqH0KggL5xIy3saRAAgmTmRqnktfEVvGLeipCbFjA0ewFbs+OZzWlyzQ6yxtNqKGD0HiATEIHE5L9BaOHdYu1TP8gTVXk7ofPOaY6aF3Nvclh1XscrhPvCk708GJ9CLY0QP7yrchC7Y6ihh5bqrMwf+NvFDjtt5+rznm/Bjugxn4NNpCYyJvGSJSD1KfpMhRmNnx+0kIPDrqe638T990mNsFuiy6dkqrhs70EI1dOmjSef25OHZxvA/bVKz3E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
