travis:
  secure:
    BINSTAR_TOKEN: viHO6/4qE/sW5iM0pbk3LUBm/Qpj6lj8XFLgXNjrWED8cfK+Kj/f70LiKalaPoLRXIMpmLfnVCiaEaf/TycvSFrlqzkJdBgqyVRrupDAywV85POID2ratiN3uTh82uMwW0PAiCptt1fG30b+AGsOWbR3BHAib2ItxaeywLbSTjMmSzVuSrAWZ/n14nm7sExGbK2yUkYPyGEvon0jsQEs3FUSQjyQiAozPTIHQ5lOar0vOpKA1g61q9DD9oMbEqsHyQeDL8V+DlouI+Y8a0DI74PhN1ZmPqeIyClUOfsdb+NkoCpAmxb5GOlZ31Dw9+y8lXKbwlhZIDfBViW3vdPKypwiSMGOEEJFFyu4Sh8RnRhwilDLV0KDJ78lcbgenz54gBSwVAlJ4+XtKNqgS2EUM+Xof3CMkVE3J1o0Nwr4tqWvLD1BuCoxbNCsdAH8BD8joO2OIVGFVCHPwBSxaSLKkXKprrLtbwQ7GH5+s8PTSzKlC1HRE9znrmiu60vzNcO0838HzXXh2bKCDu46lHe15iSRrMqsTNpvovijGYtiZk7kPeo0KQdcpyZz3UJJpHANyf6QkdeYwnrUMBF0AMUv7fU2jsbhSBf6+GQzWdLJOFNl+XlM0byXHtOnN7zq2fYdR+91VteVCBIxd8gIFiemssm33t76pFv3/AMmE2nWZXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
